---
title: "PS270 Final Project"
author: "Natalie Thuente"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---


## Project thoughts

10/13 Checkpoint 2:

Research Question: Is one political party more likely to post inaccurate or misleading data on social media than the other?
My hypothesis is that the Republican party is more likely to curate false social media content. My behavioral explanation of this is rooted in recent Republican political events and the overall negatively charged hostility since the 2020 election. The Republican party has been outspokenly discontent with the results of the 2020 election, culminating in the January 6th insurrection. These feelings of hostility have been expressed through many social media posts, and I believe that these extreme views in an abundance of emotional content could explain a lack of accuracy in Republican social media posts.
Explanatory variable of interest: Partisan affiliation of the social media post, measured by the partisan identity of the account creating the post
Response variable: Accuracy of post
To disprove my hypothesis, the amount of inaccurate posts created by Democratic accounts would have to be greater than that of Republican accounts

data from: https://www.kaggle.com/datasets/mrisdal/fact-checking-facebook-politics-pages/data

```{r}
library(tidyverse)
facebook <- read_csv("facebook-fact-check.csv")
facebook
```

